os:
    - linux
    - osx

sudo: required

env:
    global:
        - PACKAGE="MarkdownTOC"
    matrix:
        - SUBLIME_TEXT_VERSION="3"

before_install:
    - curl -OL https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/travis.sh
    - sudo pip install codecov coverage

install:
    - sh travis.sh bootstrap

script:
    - sh travis.sh run_tests
    - coverage run tests/base.py
    # testing syntax_test files
    # - sh travis.sh run_syntax_tests

after_success:
    - codecov -t e41883b8-547a-4728-a703-d8e1bbedfcf8

notifications:
    email: true
