os:
    - linux
    - osx

sudo: required

env:
    global:
        - PACKAGE="MarkdownTOC"
    matrix:
        - SUBLIME_TEXT_VERSION="3"

before_install:
    - curl -OL https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/travis.sh
    - pip install codecov

install:
    - sh travis.sh bootstrap

script:
    - sh travis.sh run_tests
    # testing syntax_test files
    # - sh travis.sh run_syntax_tests

after_success:
    - codecov

notifications:
    email: true
